float64 probability
int64 xmin
int64 ymin
int64 xmax
int64 ymax
float64 center_x
float64 center_y
float64 center_z
int16 id
int16[] type # {'YellowLeftArrow':0, 'RedLeftArrow':1, 'FlashingYellowBall':2, 'FlashingRedBall':3, 'GreenBall':4, 'YellowBall':5, 'RedBall':6, 'None':7, 'FlashingYellowRightArrow':8, 'FlashingRedRightArrow':9, 'GreenRightArrow':10, 'YellowRightArrow':11, 'RedRightArrow':12, 'FlashingYellowLeftArrow':13, 'FlashingRedLeftArrow':14, 'GreenLeftArrow':15}
